### ISSUE TITLE
Spelling error in the description of iOS app

### ISSUE THREAD

**Issue by Whalewhalewell** [folkehelseinstituttet/Fhi.Smittestopp.App#195]
The second line of the english description of the App in the App Store says "Completely voulantary".

**Comment by nc-kano** [comment]
@Whalewhalewell thank you for your information. We will look at it together with FHI

**Comment by pavshr** [comment]
I have fixed the typo in App Store Connect, the change is expected to take place with next release.

**Comment by pavshr** [comment]
Actually, the text has already been updated by Apple.
<img width="471" alt="image" src="https://user-images.githubusercontent.com/14860255/103760205-10200000-5015-11eb-9a1a-59e43dd8e822.png">

Closing the issue :)
