### ISSUE TITLE
[Issue76] Add support for ios 12.5

### ISSUE THREAD

**Issue by alberten** [folkehelseinstituttet/Fhi.Smittestopp.App#200]
https://support.apple.com/en-us/HT209084#125

**Comment by stemnic** [comment]
Enig ser ikke store grunne til at dette ikke bør være mulig å fikse. Dette åpner dørene for at eldre ios enheter som iphone 6 også er støtret

**Comment by nc-kano** [comment]
Thank you for your input. This feature is currently in consideration.

**Comment by Frederik-S-N-dk** [comment]
The feature has been approved FHI and we will start implementing the feature in the near future.

**Comment by Frederik-S-N-dk** [comment]
iOS 12.5 support has now been released and is available in the version 2.1 of the Smittestopp app.
