### ISSUE TITLE
Trying to use both the Norwegian and Danish app at the same time causes one to not function

### ISSUE THREAD

**Issue by AlfHou** [folkehelseinstituttet/Fhi.Smittestopp.App#204]
I am Norwegian, but I am studying in Denmark. Trying to have both Smittestopp apps active at the same time causes one to say it's not activated.

Steps to reproduce:

- Download both the Norwegian and Danish Smittestopp apps
- Activate both

One of them should now say that it's not active

**Comment by CUSL78** [comment]
Hi I just tried to reproduce this on my own phone. When the Danish is active the Norwegian one is put to inactive, this after a warning telling that you can only have on exposure notification warning at the time, so you have to choose whether the Norwegian or the Danish one is set to active. In this case I set the Danish to active and then the Norwegian one was set to inactive. Do you not get the warning telling you can only have one app to notify you at the time? And in that warning the possibility to switch between the Norwegian and the Danish app?

**Comment by pavshr** [comment]
Hello @AlfHou,

Thank you for your issue! However, this is not something that we developers have control over. Both on iOS and Android only one app can be active at time. This is a restriction set by Apple and Google.

**Comment by AlfHou** [comment]
@pavshr that's what I feared. I think this is a big drawback in the solution, but I totally understand that you can't do anything about it. 

@CUSL78 I can see the warning, however I don't think I found a easy solution to switch which app to use, other than uninstalling the Norwegian one and installing it againg later.

**Comment by pavshr** [comment]
@AlfHou 

You can keep the Norwegian app and have it as inactive. In this case when you make it active again and when it will perform next pull from server, it will catch up all of the keys for the days it has been inactive (up to two weeks in the past). If you delete it, and then install again after some time, your next pull will be done only for the day when the app was installed.
