### ISSUE TITLE
[Issue 94] Feature - Separate notifications

### ISSUE THREAD

**Issue by joveice** [folkehelseinstituttet/Fhi.Smittestopp.App#205]
Sometimes the notification "Smittestopp henter informasjon" (no.fhi.smittestopp_exposure_notification) wakes the phone and plays a sound since I have the settings for notifications on the app to play sound. It's not always, but sometimes which is a bit annoying as it just wakes the phone and then disappears again and has no meaning to me.

As a end user I would like to be notified with sound++ if I have been around someone who has tested positive without the "debuging" notification which is of no use to me as a normal user.

I would suggest separating notifications using the notification system the OS provides, like done in other apps when you have "best friend", "call from best friend", "chats" etc, here I can mute those I don't care about and make some ignore DnD settings if they are important. Newer android supports this, I can not talk for iOS as I don't know anything there.

OS: Android 10

**Comment by nc-kano** [comment]
@joveice  Thank you for your message. We are aware of the issue and we will try to improve it as soon as possible.

**Comment by joveice** [comment]
The notification has recently changed from coming at intervals to staying on permanently and is not dismissable.

Happened yesterday on all the phones I have access to (3). Turning off and on the app does only remove it until the app is on again. Reboot of the device does not solve it.

**Comment by nc-kano** [comment]
Thank you for your message. We are investigating the issue.
There is a separate issue for this #238

**Comment by Frederik-S-N-dk** [comment]
A solution proposal has been given and awaiting prioritization from FHI.

**Comment by Frederik-S-N-dk** [comment]
The feature has been approved FHI and we will start implementing the feature in the near future.

**Comment by Frederik-S-N-dk** [comment]
This feature has been implemented and is released in version 2.1 of the Smittestopp app which was released today.
