### ISSUE TITLE
App periodically stops working

### ISSUE THREAD

**Issue by huaracheguarache** [folkehelseinstituttet/Fhi.Smittestopp.App#222]
I have two Android devices, one Nokia 8.1 and one Samsung S20 FE 4G. On the Nokia Smittestopp works flawlessly, but on the Samsung the app periodically stops working and "Smittestopp har stoppet å virke, trykk for å reaktivere" shows up in the notifications. I have tried disabling battery optimisation for the app, but the problem still remains. Looking at the reviews on Google Play it also seems like a few other people are experiencing the same issue, notably those with OnePlus phones.

**Comment by joveice** [comment]
Experiencing this myself on Android 10 Huawei P30 Pro.
However each time I open the app it seems to still be running if not opening the app is enough to re-enable it.

I'm getting this maybe 1-2 times every 2 days or so.

> This could be a Huawei thing for me at least as their battery manager is know to break stuff as it is really intense.

**Comment by CUSL78** [comment]
@nc-kano Hi have you registered this bug in Azure devops yet?

@joveice @huaracheguarache Hi thanks for your report. We will investigating it further.

**Comment by nc-kano** [comment]
@CUSL78 There is toolkit issue for it

**Comment by pavshr** [comment]
Hello, according to[ this blog-post for German team](https://www.coronawarn.app/en/faq/#battery_optimization_background), 

> When you switch on the prioritized background activity on some Android devices, the battery optimization for the Corona-Warn-App is not turned off on OS level. This is a known limitation for a limited number of Android devices. To turn off the battery optimization accordingly, restart your device.

Can you see restart will resolve the issue on the devices you have @joveice, @huaracheguarache 

We are following closely on this issue that is a known "trouble area" for ENF apps on Android due to diversity of OEMs. 

Thank you.

**Comment by huaracheguarache** [comment]
@pavshr Ok, just rebooted the Samsung and double checked that battery optimisation is disabled for Smittestopp. Will get back to you if the app stops again.

**Comment by huaracheguarache** [comment]
@pavshr Unfortunately the app stopped working again during the night, and I had to tap the notification to reactivate it.

**Comment by jonasofrich** [comment]
@huaracheguarache 
Can you please verify that you have done all of these steps?

- Disable Put unused apps to sleep
- Disable Auto-disable unused apps
- Remove Smittestopp from the list of sleeping apps
- Disable background restrictions for Smittestopp

**Comment by joveice** [comment]
@huaracheguarache 

I had done all this and rebooted before I commented, but for my end I think maybe 2 days after I commented here the problem was gone. I have not had it since.

**Comment by joveice** [comment]
@huaracheguarache 

I had done all this and rebooted before I commented, but for my end I think maybe 2 days after I commented here the problem was gone. I have not had it since.

**Comment by huaracheguarache** [comment]
@jonasofrich 
> Can you please verify that you have done all of these steps?
> 
>     * Disable Put unused apps to sleep

Ok, I hadn't done this, but it's disabled now.
> 
>     * Disable Auto-disable unused apps

This option is not available on Android 11 as far as I know.
> 
>     * Remove Smittestopp from the list of sleeping apps

I've previously added Smittestopp to the list of apps that never sleep, and it's staying there unless you say that I should remove it.
> 
>     * Disable background restrictions for Smittestopp

The app is already allowed to work in the background.

I rebooted the phone and opened the app to make sure that it's working. You'll hear from me again if it stops working or if this solves the issue.

**Comment by huaracheguarache** [comment]
@jonasofrich Unfortunately I got a notification today that Smittestopp has stopped. While the notification was active I noticed that Smittestopp was performing an exposure check. I don't know if this is useful info, but I thought I should add it.

**Comment by Frederik-S-N-dk** [comment]
This is being handled as a bug by the app development team.
Resolving the bug is in progress.

**Comment by jonasofrich** [comment]
Closing this, as it should be resolved by #269 

@huaracheguarache Please feel free to verify this and report back if you still experience this.

**Comment by huaracheguarache** [comment]
I can confirm that everything appears to be working as it should now. Thanks!

**Comment by joveice** [comment]
I seem to still get this every once in awhile.
