### ISSUE TITLE
Implement new Exposure Notification API

### ISSUE THREAD

**Issue by huaracheguarache** [folkehelseinstituttet/Fhi.Smittestopp.App#223]
As can be seen [here](https://www.turing.ac.uk/blog/updates-algorithm-underlying-nhs-covid-19-app) and in [Google's official documentation](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#modes), Google has updated their underlying Exposure Notification API to provide improved risk calculation. I tried determining whether Smittestopp uses the improved API by searching for ExposureWindow in the repos of Folkehelseinstituttet, but I didn't get any hits, so it seems like the legacy API is in use. I admit that this is a rather naive way of trying to figure this out, and I might be wrong.

**Comment by nc-kano** [comment]
@huaracheguarache Thank you for the message. Yes, currently we are using the legacy mode as we are limited to Xamarin.ExposureNotifications solution. There is already a pull request in Xamarin repository with this feature so we hope it will be published soon.

**Comment by huaracheguarache** [comment]
Is it this [one](https://github.com/xamarin/XamarinComponents/pull/955)? In that case they're really dragging their feet given that it opened in August of last year.

**Comment by pavshr** [comment]
Xamarin team have implemented it, but due to specifics of the Exposure Notification app development, they cannot really test the changes themselves. Until it is tested they cannot merge it and release it as a stable Nuget package as I understand. We are currently prioritizing other tasks and do not have resources to test the implemented changes by Xamarin from a preview Nuget feed. Client is aware of this, so we will update the issue as soon as we get more info.

**Comment by Frederik-S-N-dk** [comment]
Resolving this is in progress.

Resolving this issue is undergoing for the Danish Smittestop app - thus, we are awaiting the testing results from them before we implement the same solution on the Norwegian Smittestopp app.

**Comment by Frederik-S-N-dk** [comment]
A solution proposal has been sent to FHI. 
Awaiting further decisions.

**Comment by Frederik-S-N-dk** [comment]
The new EN API has been planned to part of a release in the begging of April.

**Comment by keiji** [comment]
Congratulations on your migration!

I am a collaborator of COCOA(Contact-Confirming Application in Japan).

We are planning to migrate to new API with Xamarin.

And I have a question.
Where can we get `Xamarin.ExposureNotification.0.16.0-alpha` ? Did you build this yourself?

https://github.com/folkehelseinstituttet/Fhi.Smittestopp.App/blob/dev-R3.0/NDB.Covid19/TempNugetFeed/Xamarin.ExposureNotification.0.16.0-alpha.nupkg

**Comment by nc-kano** [comment]
@keiji Hello. Thank you for kind words. Yes, we had built the package ourselves from sources.

**Comment by keiji** [comment]
Thank you!
Keep in touch.

**Comment by Michael-Olesen** [comment]
This issue has been released today in version 3.0 of the Smittestopp app.
