### ISSUE TITLE
Change 'må'/'must' to 'kan'/may'

### ISSUE THREAD

**Issue by OsirisTerje** [folkehelseinstituttet/Fhi.Smittestopp.App#235]
The information in the current string "Smittestopp must have access to mobile data" is in conflict with the information on the next string ("When you turn off mobile data here, you can control your data usage. If you choose to turn off mobile data, information about infected people you have been nearby to is only obtained when you have a Wi-Fi connection. The app remains active even if you choose to turn off mobile data.")

Knowing that this is based on a danish language app, this looks like a mistranslation from danish 'må'. The correct translation from danish 'må' would be english 'may' or norwegian 'kan'.

Solved in PR #198

**Comment by HegeTorrissen** [comment]
@Frederik-S-N-dk Terje S. created this yesterday, can you update the sheet?

**Comment by HegeTorrissen** [comment]
@Frederik-S-N-dk Created bug 52147 in Azure devops.

**Comment by Frederik-S-N-dk** [comment]
@HegeTorrissen Do you have a link? I don't see it

**Comment by jonasofrich** [comment]
Fixed in https://github.com/folkehelseinstituttet/Fhi.Smittestopp.App/pull/244
