### ISSUE TITLE
Diverse norsk bokmål feil

### ISSUE THREAD

**Issue by OsirisTerje** [folkehelseinstituttet/Fhi.Smittestopp.App#236]

**Comment by HegeTorrissen** [comment]
@Frederik-S-N-dk Terje S. created this yesterday, can you update the sheet?

**Comment by HegeTorrissen** [comment]
@Frederik-S-N-dk Created bug 52145 in Azure devops.

**Comment by Frederik-S-N-dk** [comment]
@HegeTorrissen Do you have a link? I don't see it

**Comment by HegeTorrissen** [comment]
@Frederik-S-N-dk https://fhi.visualstudio.com/Fhi.Handhygiene/_workitems/edit/52145?triage=true

**Comment by HegeTorrissen** [comment]
@Frederik-S-N-dk Sorry, wrong project, I will change it :-)

**Comment by jonasofrich** [comment]
Fixed in https://github.com/folkehelseinstituttet/Fhi.Smittestopp.App/pull/244
