### ISSUE TITLE
[Issue 78] Exposure only counts within 10 days from testing date

### ISSUE THREAD

**Issue by Frederik-S-N-dk** [folkehelseinstituttet/Fhi.Smittestopp.App#255]
This issue is prioritized and will be part of a 2.x release.
In below table some examples are given:
![image](https://user-images.githubusercontent.com/60694331/104924407-a9e49700-599d-11eb-977b-68042e3443a4.png)

**Comment by Michael-Olesen** [comment]
This issue has been released today in version 3.0 of the Smittestopp app.
