### ISSUE TITLE
Add link to GitHub repository

### ISSUE THREAD

**Issue by huaracheguarache** [folkehelseinstituttet/Fhi.Smittestopp.App#280]
I want to propose adding a link to this GitHub repository on the Google Play and App Store pages to encourage people to report bugs here.

**Comment by Frederik-S-N-dk** [comment]
@huaracheguarache Thanks for your input! 
We will discuss this suggestion with FHI.

**Comment by Michael-Olesen** [comment]
The link has been added to App Store page today with version 3.0 of Smittestopp, and will be added to Google Play soon.

**Comment by huaracheguarache** [comment]
That's good news! However, I have noticed that the link on the Google Play page of Smittestopp to the Helsenorge information page on Smittestopp doesn't work on my smartphone. The problem appears to be due to the full stop at the end of the link:

`Smittestopp is developed by the Norwegian Institute of Public Health. Read more about the app on www.helsenorge.no/en/smittestopp.`

The full stop is included in the link when I tap it to open the webpage, which results in a 500 error code:

![Screenshot_20210527-003934](https://user-images.githubusercontent.com/33153877/119740418-2b848e00-be84-11eb-805e-8620f3608936.png)

**Comment by Michael-Olesen** [comment]
@huaracheguarache Thanks for the input, you are right about the full stop, we will remove that from the English description

**Comment by Michael-Olesen** [comment]
The link has now been added to the Google Play page, and the full stop has been removed from the English description link.
