### ISSUE TITLE
Incompatible license

### ISSUE THREAD

**Issue by perbu** [folkehelseinstituttet/Fhi.Smittestopp.App#3]
Thanks for releasing this.

Please be aware that the GPL 2.0 license is incompatible with distribution in the Apple App store. The gist of it is that the GPL2 does not allow restrictions to be placed on distribution of source and binaries. This is in direct conflict with the Apple App store ToS.

See the FSF clarification for further details:
[https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement](https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement)

My suggestion is to find a somewhat more liberal license to distribute. You could, if you have full copyright, use a dual license scheme, but that gets complex as well. Might as well just use a liberal license.

Good luck with this and all the best.

At your service,

Per.

**Comment by OsirisTerje** [comment]
@perbu  Thanks for bringing this to our attention!  We're looking into it and how it can be resolved.

**Comment by OsirisTerje** [comment]
@perbu The decision was a change to a permissive license.  Pull Requests in progress.    Thank your for your contribution!  It is really appreciated.
