### ISSUE TITLE
Transmission risk configuration seems incorrect

### ISSUE THREAD

**Issue by jarib** [folkehelseinstituttet/Fhi.Smittestopp.App#41]
The variable `DAYS_SINCE_ONSET_FOR_TRANSMISSION_RISK_CALCULATION` in the [current config](https://github.com/folkehelseinstituttet/Fhi.Smittestopp.App/blob/1e9d0c98e7889ab9cf7fe571f72905c562311677/NDB.Covid19/NDB.Covid19/Configuration/Conf.cs#L51-L62) and [the corresponding code](https://github.com/folkehelseinstituttet/Fhi.Smittestopp.App/blob/1e9d0c98e7889ab9cf7fe571f72905c562311677/NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/UploadDiagnosisKeysHelper.cs#L107-L126) indicates that the "transmission risk level" will be calculated to be highest 11-12 days after symptom onset. 

However, the scientific literature (see e.g. [1](https://www.nature.com/articles/s41591-020-0869-5), [2](https://www.medrxiv.org/content/10.1101/2020.09.04.20188516v2), [3](https://www.medrxiv.org/content/10.1101/2020.09.28.20202028v1)) has the transmission risk at its highest right before or at symptom onset.

The same calculation appears to be [duplicated in the backend](https://github.com/folkehelseinstituttet/Fhi.Smittestopp.Backend/blob/46347baf1b5a46e22f2d47fdf1dda8888c86f0a0/DIGNDB.App.SmitteStop.Core/Helpers/RiskCalculator.cs#L20-L47). It also a bit worrisome that the tests for this code appears to be [disabled](https://github.com/folkehelseinstituttet/Fhi.Smittestopp.App/blob/1e9d0c98e7889ab9cf7fe571f72905c562311677/NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/TransmissionRiskCalculationTest.cs#L21-L23). 

Unless I'm misunderstanding how the "transmission risk level" is used, this looks like a bug.

**Comment by pavshr** [comment]
@jarib 
Thanks for creating the issue. The tests are temporarily ignored and shall be enabled soon. Unsure if we got final confirmation regarding the values. I am adding a milestone to this issue.

However, there is a clarification needed. The app is not assigning the risk score for the keys by setting TransmissionRiskLevel on temporary exposure keys, it is assigning the risk level. And then each app decides what this risk level represents ([src](https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration/3586323-transmissionrisklevelvalues)). 

What we are doing here is that we are setting the risk level to be an index of some score in transmissionRiskLevelValues array of the Configuration object. Later on, it resolves to some score when the other phone downloads the keys together with Configuration from server. You can see the values that are assigned to each key in the appsettings file of the server [here](https://github.com/folkehelseinstituttet/Fhi.Smittestopp.Backend/blob/46347baf1b5a46e22f2d47fdf1dda8888c86f0a0/DIGNDB.App.SmitteStop.API/appsettings.json#L63). So only the keys that are created close before/after the symptoms onset date will reflect in the highest risk score from configuration, namely 8. While keys from other days are assigned lowest risk score 1.

**Comment by jarib** [comment]
Aha, I see. Thanks for clarifying. That makes more sense. I couldn't see any place in the backend code where the index is used for lookup in the `TransmissionRiskScores` config though. 

Feel free to close the issue.

**Comment by pavshr** [comment]
@janw83 that is not backend that does it, translation of risk level to risk score is done by EN API on the device when we provide the keys and configuration to it.

**Comment by pavshr** [comment]
The test is reworked and no longer ignored.
